package xcache

import (
	"github.com/pubgo/xerror"
)

var (
	// ErrXCache ...
	ErrXCache = xerror.New("xcache error")
	// ErrKeyNotFound ...
	ErrKeyNotFound = ErrXCache.New("key不存在")
	// ErrLength ...
	ErrLength = ErrXCache.New("数据超过了最大的长度限度或者小于最小的长度限度")
	// ErrBufSize ...
	ErrBufSize = ErrXCache.New("现有的缓存超过了最大的限度或者小于最小的限度")
	// ErrBufExceeded ...
	ErrBufExceeded = ErrXCache.New("现有的缓存超过了最大的缓存限制")
	// ErrExpiration ...
	ErrExpiration = ErrXCache.New("过期时间超过了最大的过期时间或者小于最小的过期时间")
	// ErrClearTime ...
	ErrClearTime = ErrXCache.New("定时清理过期缓存时间错误")
	ErrClearNum  = ErrXCache.New("定时清理过期缓存数量错误")
	// ErrDataLoadTime ...
	ErrDataLoadTime = ErrXCache.New("数据加载函数时间设置错误")
	// ErrDataLoadTimeout...
	ErrDataLoadTimeout = ErrXCache.New("数据加载超时")
)
